Repository DOSOPT-CDS-APP-TEAM5/Carrot-iOS, pull requests merged in 2023-11, with the labels that each got.

#3 [Setting] - #2 프로젝트 템플릿 설정
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ Setting, 🤡 희재

#4 Setting/#1
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Carrot-iOS/Carrot-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Carrot-iOS/Carrot-iOS/Application/AppDelegate.swift
  Carrot-iOS/Carrot-iOS/Application/SceneDelegate.swift
  Carrot-iOS/Carrot-iOS/Data/Club/1.swift
  Carrot-iOS/Carrot-iOS/Data/Detail/1.swift
  Carrot-iOS/Carrot-iOS/Data/Main/1.swift
  Carrot-iOS/Carrot-iOS/Data/SignUp/1.swift
  Carrot-iOS/Carrot-iOS/Global/Constant/1.swift
  Carrot-iOS/Carrot-iOS/Global/Extension/1.swift
  Carrot-iOS/Carrot-iOS/Info.plist
  Carrot-iOS/Carrot-iOS/Network/Foundation/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Base/ViewController.swift
  Carrot-iOS/Carrot-iOS/Presentation/Club/Cell/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Club/View/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Club/ViewController/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/Cell/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/ViewController/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/ViewController/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/SignUp/Cell/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/SignUp/View/1.swift
  Carrot-iOS/Carrot-iOS/Presentation/SignUp/ViewController/1.swift
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/Contents.json
  Carrot-iOS/Carrot-iOS/Resource/Base.lproj/LaunchScreen.storyboard
Labels: ⚙️ Setting, 🤖 윤학, 🎃 태경

#12 [Style] #11 - 모임 더 둘러보기 화면, 서치바 추가
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS/Presentation/Club/ViewController/13.swift
  Carrot-iOS/Carrot-iOS/Presentation/Club/ViewController/ClubViewController.swift
Labels: ✨ Feature, 🎃 태경

#17 [Style] #14 - 네비게이션 바 & 모임 더 둘러보기 뷰 구현
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS/Application/SceneDelegate.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/8.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/MainMoreClubCollectionViewCell.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/9.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainMoreClubCollectionFooterView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainMoreClubCollectionView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainTopView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/MainView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/ViewController/10.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/ViewController/MainViewController.swift
Labels: ✨ Feature, 🤡 희재

#21 [Fix] 새로운 Font 폴더로 대체 #20
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
Labels: ⛏ Fix, 🤖 윤학

#23 [Chore] UIFont+의 폰트 선언을 메서드에서 변수로 수정
  Carrot-iOS/Carrot-iOS/Global/Extension/UIKit+/UIFont+.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/MainCategoryCollectionViewCell.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/MainMoreClubCollectionViewCell.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/MainPostCollectionViewCell.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainMoreClubCollectionFooterView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainTopView.swift
Labels: 🥢 Chore, 🤖 윤학

#25 [Style] #13 - 모임 더 둘러보기 화면, 네비게이션바 구현
  Carrot-iOS/Carrot-iOS/Presentation/Club/ViewController/ClubViewController.swift
Labels: ✨ Feature, 🎃 태경

#28 [Style] 모임 가입하기 화면, 상단 배너 구현
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS/Global/Extension/UIKit+/UILabel+.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/15.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/AssistantView/DetailBannerImageView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/AssistantView/DetailDescriptionView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/AssistantView/DetailTagLabel.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/AssistantView/DetailTopView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/DetailView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/ViewController/16.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/ViewController/DetailViewController.swift
Labels: ✨ Feature, 🤖 윤학

#29 [Feat] #27 - 글쓰기 커스텀 플로팅 버튼 구현
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/AssistantView/MainFloatingButton.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/View/MainView.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/ViewController/MainViewController.swift
Labels: ✨ Feature, 🤡 희재

#34 [Style] #32 - 마이페이지 UI 구현
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS/Global/Constant/Image.swift
  Carrot-iOS/Carrot-iOS/Presentation/Detail/View/AssistantView/DetailTopView.swift
  Carrot-iOS/Carrot-iOS/Presentation/SignUp/View/SignUpView.swift
  Carrot-iOS/Carrot-iOS/Presentation/SignUp/ViewController/SignUpViewController.swift
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/ic_editprofile.imageset/Contents.json
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/ic_editprofile.imageset/Frame 310.png
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/ic_editprofile.imageset/Frame 310@2x.png
  Carrot-iOS/Carrot-iOS/Resource/Assets.xcassets/ic_editprofile.imageset/Frame 310@3x.png
Labels: ✨ Feature, 🤡 희재

#37 [Setting] #30 - 네트워크 세팅하기
  Carrot-iOS/Carrot-iOS.xcodeproj/project.pbxproj
  Carrot-iOS/Carrot-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Carrot-iOS/Carrot-iOS/Application/SceneDelegate.swift
  Carrot-iOS/Carrot-iOS/Data/Main/Model/MainModel.swift
  Carrot-iOS/Carrot-iOS/Domain/Entity/Club/ClubEntity.swift
  Carrot-iOS/Carrot-iOS/Domain/Entity/Detail/DetailEntity.swift
  Carrot-iOS/Carrot-iOS/Domain/Entity/Main/MainEntity.swift
  Carrot-iOS/Carrot-iOS/Global/Constant/URLs.swift
  Carrot-iOS/Carrot-iOS/Global/Extension/ThirdPartyLibs+/Moya+.swift
  Carrot-iOS/Carrot-iOS/Info.plist
  Carrot-iOS/Carrot-iOS/Network/DTO/CLub/ClubDTO.swift
  Carrot-iOS/Carrot-iOS/Network/DTO/Common/GenericResponse.swift
  Carrot-iOS/Carrot-iOS/Network/DTO/Common/SimpleResponse.swift
  Carrot-iOS/Carrot-iOS/Network/DTO/Common/VoidResult.swift
  Carrot-iOS/Carrot-iOS/Network/DTO/Detail/DetailDTO.swift
  Carrot-iOS/Carrot-iOS/Network/DTO/Main/MainDTO.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/7.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/APIConstant.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/BaseService.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/BaseTargetType.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/Config.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/MoyaLoggingPlugin.swift
  Carrot-iOS/Carrot-iOS/Network/Foundation/NetworkResult.swift
  Carrot-iOS/Carrot-iOS/Network/Main/MainAPI.swift
  Carrot-iOS/Carrot-iOS/Network/Main/MainService.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Repository/ClubRepository.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Repository/DetailRepository.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Repository/MainRepository.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Transform/ClubTransform.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Transform/DetailTransform.swift
  Carrot-iOS/Carrot-iOS/NetworkData/Transform/MainTransform.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/Cell/MainPostCollectionViewCell.swift
  Carrot-iOS/Carrot-iOS/Presentation/Main/ViewController/MainViewController.swift
Labels: ⚙️ Setting, ✨ Feature, 🤡 희재
